# Generated by Django 2.1 on 2018-08-30 11:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingresar un género para la publicacion (e.g. Urgente, Noticia, Notificacion, etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para este libro particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Ingrese una descripcion breve de la publicacion', max_length=500)),
                ('isbn', models.CharField(help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('text', models.TextField(help_text='Ingrese la noticia breve de la publicacion', max_length=2000)),
                ('postDate', models.DateField()),
                ('status', models.CharField(choices=[('b', 'Borrador'), ('e', 'Eliminado'), ('d', 'Denunciado'), ('p', 'Publicado')], default='b', help_text='Estado dela publicacion', max_length=1)),
                ('genre', models.ManyToManyField(help_text='Seleccione el genero de esta publiacion', to='catalog.Genre')),
            ],
            options={
                'ordering': ['title', '-postDate'],
            },
        ),
    ]
