# Generated by Django 2.1 on 2018-08-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180830_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='summary',
            field=models.CharField(help_text='Ingrese una descripcion breve de la publicacion', max_length=200),
        ),
    ]
