# Generated by Django 2.1 on 2018-08-30 17:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20180830_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID único para esta publicacion particular en toda la biblioteca', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(help_text='Ingrese una descripcion breve de la docuemntacion', max_length=200)),
                ('text', models.TextField(help_text='Ingrese informacion de la documentacion', max_length=2000)),
                ('createDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('g', 'General'), ('e', 'Indivual por carrera')], default='g', help_text='Tipo de documentacion', max_length=1)),
            ],
            options={
                'ordering': ['title', '-createDate'],
            },
        ),
    ]
