# Generated by Django 2.1 on 2018-09-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_documentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentacion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
