# Generated by Django 2.1 on 2018-09-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180903_1101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentacion',
            options={'ordering': ['title', '-createDate'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
