# Generated by Django 2.1 on 2018-10-25 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('cant_años', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(null=True)),
                ('motivo_baja', models.CharField(max_length=200)),
                ('estado_comentario', models.CharField(blank=True, choices=[('p', 'Publicado'), ('b', 'Borrador'), ('d', 'Denunciado'), ('e', 'Eliminado')], default='b', help_text='situacion actual del comentario', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_invited', models.DateTimeField(default=django.utils.timezone.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='auth.Group')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_invitations', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GroupProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_members', models.BooleanField(default=False)),
                ('admins', models.ManyToManyField(related_name='admin_of', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='', max_length=50)),
                ('año', models.IntegerField(default=0)),
                ('carrera', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='MeGusta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('cuerpo', models.TextField(max_length=5000)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('tipo_publicacion', models.CharField(blank=True, choices=[('n', 'Noticia'), ('d', 'Documentacion'), ('f', 'Foro'), ('g', 'Grupo')], default='d', help_text='tipo de publicacion', max_length=1)),
                ('estado_publicacion', models.CharField(blank=True, choices=[('p', 'Publicado'), ('b', 'Borrador'), ('d', 'Denunciado'), ('e', 'Eliminado')], default='b', help_text='situacion actual de la publicacion', max_length=1)),
                ('alcance', models.CharField(blank=True, choices=[('g', 'Global'), ('e', 'Expecifico')], default='g', help_text='alcance de la publicacion', max_length=1)),
                ('aprovacion', models.IntegerField(blank=True, default=0, null=True)),
                ('denuncias', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, default='#', null=True, upload_to='images/')),
                ('materia', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Materia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('eMail', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaAlta', models.DateField(auto_now_add=True)),
                ('fechaBaja', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('a', 'Administrador'), ('e', 'Estudiante')], default='e', help_text='tipo de usuario', max_length=1)),
                ('estado', models.CharField(blank=True, choices=[('p', 'Pendiente de activación'), ('a', 'Activo'), ('s', 'Suspendido'), ('e', 'Eliminado')], default='p', help_text='estado actual del usuario', max_length=1)),
                ('tokenActivacion', models.CharField(blank=True, max_length=40, null=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Carrera')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='megusta',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Publicacion'),
        ),
        migrations.AddField(
            model_name='megusta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Publicacion'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Publicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
