# Generated by Django 2.1 on 2018-09-25 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=1000)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(null=True)),
                ('motivo_baja', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPublicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cometario',
            name='publicacion',
        ),
        migrations.RemoveField(
            model_name='cometario',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='cuerpo',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Cometario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='estado_comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.EstadoPublicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Publicacion'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado_publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.EstadoPublicacion'),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.TipoPublicacion'),
        ),
    ]
