# Generated by Django 2.1 on 2018-10-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='grupo',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
