# Generated by Django 2.1 on 2018-09-26 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180926_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='Materia',
            new_name='materia',
        ),
    ]
