# Generated by Django 2.1 on 2018-10-26 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20181025_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='grupo',
        ),
    ]
