# Generated by Django 2.1 on 2018-09-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180926_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='publicacion',
            name='materia',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
    ]
