# Generated by Django 2.1 on 2018-10-27 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usuario_descripcion'),
        ('home', '0005_groupinvitation_groupproperties'),
    ]

    operations = [
    ]
