# Generated by Django 2.1 on 2018-09-29 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20180926_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=50)),
                ('apellido', models.CharField(default='', max_length=50)),
                ('eMail', models.EmailField(max_length=254)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fechaAlta', models.DateField(auto_now_add=True)),
                ('fechaBaja', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('a', 'Administrador'), ('e', 'Estudiante')], default='e', help_text='tipo de usuario', max_length=1)),
                ('estado', models.CharField(blank=True, choices=[('p', 'Pendiente de activación'), ('a', 'Activo'), ('s', 'Suspendido'), ('e', 'Eliminado')], default='p', help_text='estado actual del usuario', max_length=1)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Carrera')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='materia',
            name='carrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Carrera'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='alcance',
            field=models.CharField(blank=True, choices=[('g', 'Global'), ('e', 'Expecifico')], default='g', help_text='alcance de la publicacion', max_length=1),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='materia',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='home.Materia'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(blank=True, choices=[('n', 'Noticia'), ('d', 'Documentacion')], default='d', help_text='tipo de publicacion', max_length=1),
        ),
    ]
