# Generated by Django 2.1 on 2018-10-27 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('home', '0007_merge_20181027_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='grupo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
