# Generated by Django 2.1 on 2018-10-27 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_publicacion_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='usuarioDenunciado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Usuario'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='publicacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Publicacion'),
        ),
    ]
