# Generated by Django 2.1 on 2018-10-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180929_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tokenActivacion',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
