# Generated by Django 2.1 on 2018-10-04 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_usuario_tokenactivacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='materia',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Materia'),
        ),
    ]
