# Generated by Django 2.1 on 2018-10-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20181027_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='docfile',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
