# Generated by Django 2.1 on 2018-10-30 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_publicacion_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='docfile',
        ),
    ]
