# Generated by Django 2.1 on 2018-10-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20181004_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='cuerpo',
            field=models.TextField(max_length=5000),
        ),
    ]
