# Generated by Django 2.1 on 2018-10-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20181004_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
