# Generated by Django 2.1 on 2018-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20181004_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='aprovacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='denuncias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
