# Generated by Django 2.1 on 2018-10-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20181010_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(default='static/assets/images/ucsecampus.jpg', upload_to='static/'),
        ),
    ]
