# Generated by Django 2.1 on 2018-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='imagen',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(default='static/assets/images/ucsecampus.jpg', upload_to='static/assets/images'),
        ),
    ]
