# Generated by Django 2.1 on 2018-10-21 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20181012_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='cant_años',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(blank=True, choices=[('n', 'Noticia'), ('d', 'Documentacion'), ('f', 'Foro')], default='d', help_text='tipo de publicacion', max_length=1),
        ),
    ]
