# Generated by Django 2.1 on 2018-10-22 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0016_auto_20181012_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=1000, null=True)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='image',
            field=models.ImageField(blank=True, default='#', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='tipo_publicacion',
            field=models.CharField(blank=True, choices=[('n', 'Noticia'), ('d', 'Documentacion'), ('f', 'Foro')], default='d', help_text='tipo de publicacion', max_length=1),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Publicacion'),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
