# Generated by Django 2.1 on 2018-11-02 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_groupproperties_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupproperties',
            name='state',
        ),
    ]
