# Generated by Django 2.1 on 2018-11-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('home', '0017_remove_groupproperties_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, choices=[('p', 'Publicado'), ('b', 'Borrador'), ('d', 'Denunciado'), ('e', 'Eliminado')], default='b', help_text='situacion actual de la publicacion', max_length=1)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
