# Generated by Django 2.1 on 2018-10-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20181022_0900'),
        ('home', '0017_auto_20181021_1813'),
    ]

    operations = [
    ]
