# Generated by Django 2.1 on 2018-10-23 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_merge_20181022_1416'),
        ('home', '0018_megusta'),
    ]

    operations = [
    ]
