# Generated by Django 2.1 on 2018-11-02 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('home', '0018_estado_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='grupoDenunciado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
