# Generated by Django 2.1 on 2018-11-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_estado_grupo_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado_grupo',
            name='admins',
        ),
    ]
