# Generated by Django 2.1 on 2018-11-09 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0022_estado_grupo_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField(default=django.utils.timezone.now, null=True)),
                ('descripcion', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('lugar', models.CharField(blank=True, default='', max_length=80, null=True)),
                ('estado', models.CharField(blank=True, choices=[('p', 'Publicado'), ('d', 'Denunciado'), ('e', 'Eliminado')], default='b', help_text='situacion actual de la publicacion', max_length=1)),
                ('fecha_alta', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('fecha_baja', models.DateTimeField(blank=True, null=True)),
                ('motivo_baja', models.CharField(blank=True, max_length=200, null=True)),
                ('gruposInivtados', models.ManyToManyField(to='home.Publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuarioA', models.ManyToManyField(to='home.Usuario')),
            ],
        ),
    ]
