# Generated by Django 2.1 on 2018-11-11 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='gruposInivtados',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='usuarioA',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
