# Generated by Django 2.1 on 2018-11-14 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_personaevento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaevento',
            old_name='usuarioCreador',
            new_name='usuario',
        ),
    ]
